<div>
    <h2>Whois</h2>
</div>
<div class="field">
    <form action="" method="POST">
        <input class="search-box" name="whois" type="text" placeholder="sasuke.com.br">
        <input class="button-search" type="submit" name="enviar" value="Whois">
    </form>
</div>

<?php
    $domainname = strtolower($_POST['whois']);
    $port=43;

    $whoisservers = array(
        "ac" => "whois.nic.ac", // Ascension Island
        "ae" => "whois.nic.ae", // United Arab Emirates
        "aero"=>"whois.aero",
        "af" => "whois.nic.af", // Afghanistan
        "ag" => "whois.nic.ag", // Antigua And Barbuda
        "ai" => "whois.ai", // Anguilla
        "al" => "whois.ripe.net", // Albania
        "am" => "whois.amnic.net",  // Armenia
        "arpa" => "whois.iana.org",
        "as" => "whois.nic.as", // American Samoa
        "asia" => "whois.nic.asia",
        "at" => "whois.nic.at", // Austria
        "au" => "whois.aunic.net", // Australia
        "ax" => "whois.ax", // Aland Islands
        "az" => "whois.ripe.net", // Azerbaijan
        "be" => "whois.dns.be", // Belgium
        "bg" => "whois.register.bg", // Bulgaria
        "bi" => "whois.nic.bi", // Burundi
        "biz" => "whois.biz",
        "bj" => "whois.nic.bj", // Benin
        "bn" => "whois.bn", // Brunei Darussalam
        "bo" => "whois.nic.bo", // Bolivia
        "br" => "whois.registro.br", // Brazil
        "bt" => "whois.netnames.net", // Bhutan
        "by" => "whois.cctld.by", // Belarus
        "bz" => "whois.belizenic.bz", // Belize
        "ca" => "whois.cira.ca", // Canada
        "cat" => "whois.cat", // Spain
        "cc" => "whois.nic.cc", // Cocos (Keeling) Islands
        "cd" => "whois.nic.cd", // Congo, The Democratic Republic Of The
        "ch" => "whois.nic.ch", // Switzerland
        "ci" => "whois.nic.ci", // Cote d'Ivoire
        "ck" => "whois.nic.ck", // Cook Islands
        "cl" => "whois.nic.cl", // Chile
        "cn" => "whois.cnnic.net.cn", // China
        "co" => "whois.nic.co", // Colombia
        "com" => "whois.verisign-grs.com",
        "coop" => "whois.nic.coop",
        "cx" => "whois.nic.cx", // Christmas Island
        "cz" => "whois.nic.cz", // Czech Republic
        "de" => "whois.denic.de", // Germany
        "dk" => "whois.dk-hostmaster.dk", // Denmark
        "dm" => "whois.nic.dm", // Dominica
        "dz" => "whois.nic.dz", // Algeria
        "ec" => "whois.nic.ec", // Ecuador
        "edu" => "whois.educause.edu",
        "ee" => "whois.eenet.ee", // Estonia
        "eg" => "whois.ripe.net", // Egypt
        "es" => "whois.nic.es", // Spain
        "eu" => "whois.eu",
        "fi" => "whois.ficora.fi", // Finland
        "fo" => "whois.nic.fo", // Faroe Islands
        "fr" => "whois.nic.fr", // France
        "gd" => "whois.nic.gd", // Grenada
        "gg" => "whois.gg", // Guernsey
        "gi" => "whois2.afilias-grs.net", // Gibraltar
        "gl" => "whois.nic.gl", // Greenland (Denmark)
        "gov" => "whois.nic.gov",
        "gs" => "whois.nic.gs", // South Georgia And The South Sandwich Islands
        "gy" => "whois.registry.gy", // Guyana
        "hk" => "whois.hkirc.hk", // Hong Kong
        "hn" => "whois.nic.hn", // Honduras
        "hr" => "whois.dns.hr", // Croatia
        "ht" => "whois.nic.ht", // Haiti
        "hu" => "whois.nic.hu", // Hungary
        "ie" => "whois.domainregistry.ie", // Ireland
        "il" => "whois.isoc.org.il", // Israel
        "im" => "whois.nic.im", // Isle of Man
        "in" => "whois.inregistry.net", // India
        "info" => "whois.afilias.net",
        "int" => "whois.iana.org",
        "io" => "whois.nic.io", // British Indian Ocean Territory
        "iq" => "whois.cmc.iq", // Iraq
        "ir" => "whois.nic.ir", // Iran, Islamic Republic Of
        "is" => "whois.isnic.is", // Iceland
        "it" => "whois.nic.it", // Italy
        "je" => "whois.je", // Jersey
        "jobs" => "jobswhois.verisign-grs.com",
        "jp" => "whois.jprs.jp", // Japan
        "ke" => "whois.kenic.or.ke", // Kenya
        "kg" => "www.domain.kg", // Kyrgyzstan
        "ki" => "whois.nic.ki", // Kiribati
        "kr" => "whois.kr", // Korea, Republic Of
        "kz" => "whois.nic.kz", // Kazakhstan
        "la" => "whois.nic.la", // Lao People's Democratic Republic
        "li" => "whois.nic.li", // Liechtenstein
        "lt" => "whois.domreg.lt", // Lithuania
        "lu" => "whois.dns.lu", // Luxembourg
        "lv" => "whois.nic.lv", // Latvia
        "ly" => "whois.nic.ly", // Libya
        "ma" => "whois.iam.net.ma", // Morocco
        "md" => "whois.nic.md", // Moldova
        "me" => "whois.nic.me", // Montenegro
        "mg" => "whois.nic.mg", // Madagascar
        "mil" => "whois.nic.mil",
        "ml" => "whois.dot.ml", // Mali
        "mn" => "whois.nic.mn", // Mongolia
        "mo" => "whois.monic.mo", // Macao
        "mobi" => "whois.dotmobiregistry.net",
        "mp" => "whois.nic.mp", // Northern Mariana Islands
        "ms" => "whois.nic.ms", // Montserrat
        "mu" => "whois.nic.mu", // Mauritius
        "museum" => "whois.museum",
        "mx" => "whois.mx", // Mexico
        "my" => "whois.domainregistry.my", // Malaysia
        "na" => "whois.na-nic.com.na", // Namibia
        "name" => "whois.nic.name",
        "nc" => "whois.nc", // New Caledonia
        "net" => "whois.verisign-grs.net",
        "nf" => "whois.nic.nf", // Norfolk Island
        "ng" => "whois.nic.net.ng", // Nigeria
        "nl" => "whois.domain-registry.nl", // Netherlands
        "no" => "whois.norid.no", // Norway
        "nu" => "whois.nic.nu", // Niue
        "nz" => "whois.srs.net.nz", // New Zealand
        "om" => "whois.registry.om", // Oman
        "org" => "whois.pir.org",
        "pe" => "kero.yachay.pe", // Peru
        "pf" => "whois.registry.pf", // French Polynesia
        "pl" => "whois.dns.pl", // Poland
        "pm" => "whois.nic.pm", // Saint Pierre and Miquelon (France)
        "post" => "whois.dotpostregistry.net",
        "pr" => "whois.nic.pr", // Puerto Rico
        "pro" => "whois.dotproregistry.net",
        "pt" => "whois.dns.pt", // Portugal
        "pw" => "whois.nic.pw", // Palau
        "qa" => "whois.registry.qa", // Qatar
        "re" => "whois.nic.re", // Reunion (France)
        "ro" => "whois.rotld.ro", // Romania
        "rs" => "whois.rnids.rs", // Serbia
        "ru" => "whois.tcinet.ru", // Russian Federation
        "sa" => "whois.nic.net.sa", // Saudi Arabia
        "sb" => "whois.nic.net.sb", // Solomon Islands
        "sc" => "whois2.afilias-grs.net", // Seychelles
        "se" => "whois.iis.se", // Sweden
        "sg" => "whois.sgnic.sg", // Singapore
        "sh" => "whois.nic.sh", // Saint Helena
        "si" => "whois.arnes.si", // Slovenia
        "sk" => "whois.sk-nic.sk", // Slovakia
        "sm" => "whois.nic.sm", // San Marino
        "sn" => "whois.nic.sn", // Senegal
        "so" => "whois.nic.so", // Somalia
        "st" => "whois.nic.st", // Sao Tome And Principe
        "su" => "whois.tcinet.ru", // Russian Federation
        "sx" => "whois.sx", // Sint Maarten (dutch Part)
        "sy" => "whois.tld.sy", // Syrian Arab Republic
        "tc" => "whois.meridiantld.net", // Turks And Caicos Islands
        "tel" => "whois.nic.tel",
        "tf" => "whois.nic.tf", // French Southern Territories
        "th" => "whois.thnic.co.th", // Thailand
        "tj" => "whois.nic.tj", // Tajikistan
        "tk" => "whois.dot.tk", // Tokelau
        "tl" => "whois.nic.tl", // Timor-leste
        "tm" => "whois.nic.tm", // Turkmenistan
        "tn" => "whois.ati.tn", // Tunisia
        "to" => "whois.tonic.to", // Tonga
        "tp" => "whois.nic.tl", // Timor-leste
        "tr" => "whois.nic.tr", // Turkey
        "travel" => "whois.nic.travel",
        "tv" => "tvwhois.verisign-grs.com", // Tuvalu
        "tw" => "whois.twnic.net.tw", // Taiwan
        "tz" => "whois.tznic.or.tz", // Tanzania, United Republic Of
        "ua" => "whois.ua", // Ukraine
        "ug" => "whois.co.ug", // Uganda
        "uk" => "whois.nic.uk", // United Kingdom
        "us" => "whois.nic.us", // United States
        "uy" => "whois.nic.org.uy", // Uruguay
        "uz" => "whois.cctld.uz", // Uzbekistan
        "vc" => "whois2.afilias-grs.net", // Saint Vincent And The Grenadines
        "ve" => "whois.nic.ve", // Venezuela
        "vg" => "whois.adamsnames.tc", // Virgin Islands, British
        "wf" => "whois.nic.wf", // Wallis and Futuna
        "ws" => "whois.website.ws", // Samoa
        "xxx" => "whois.nic.xxx",
        "yt" => "whois.nic.yt", // Mayotte
        "yu" => "whois.ripe.net",
        "aero" => "whois.aero",
        "biz" => "whois.biz",
        "cat" => "whois.cat",
        "com" => "whois.verisign-grs.net",
        "coop" => "whois.nic.coop",
        "info" => "whois.afilias.info",
        "int" => "whois.iana.org",
        "jobs" => "jobswhois.verisign-grs.com",
        "mobi" => "whois.dotmobiregistry.net",
        "museum" => "whois.museum",
        "name" => "whois.nic.name",
        "net" => "whois.verisign-grs.net",
        "org" => "whois.pir.org",
        "pro" => "aaa.pro",
        "echt.pro" => "whois.registrypro.pro",
        "travel" => "whois.nic.travel",
        "asia" => "whois.nic.asia",
        "bike" => "whois.donuts.co",
        "accountants" => "whois.donuts.co",
        "world" => "whois.donuts.co",
        "tools" => "whois.donuts.co",
        "house" => "whois.donuts.co",
        "ab.abbott" => "whois.afilias-srs.net",
        "abogado" => "whois-dub.mm-registry.com",
        "academy" => "whois.donuts.co",
        "accentur.accountan.active" => "whois.nic.active",
        "actor" => "whois.unitedtld.com",
        "ads" => "domain-registry-whois.l.google.com",
        "adult" => "whois.afilias-srs.net",
        "afl" => "whois.nic.afl",
        "agency" => "whois.donuts.co",
        "ai.airforce" => "whois.unitedtld.com",
        "allfinanz" => "whois.ksregistry.net",
        "alsace" => "whois-alsace.nic.fr",
        "amsterda.android" => "domain-registry-whois.l.google.com",
        "apartments" => "whois.donuts.co",
        "aquarelle" => "whois-aquarelle.nic.fr",
        "archi" => "whois.ksregistry.net",
        "army" => "whois.rightside.co",
        "arpa" => "whois.iana.org",
        "associates" => "whois.donuts.co",
        "attorney" => "whois.rightside.co",
        "auction" => "whois.unitedtld.com",
        "audio" => "whois.uniregistry.net",
        "auto" => "whois.uniregistry.net",
        "autos" => "whois.afilias-srs.net",
        "ax.band" => "whois.rightside.co",
        "bank" => "whois.nic.bank",
        "bar" => "whois.nic.bar",
        "barclaycard" => "whois.nic.barclaycard",
        "barclays" => "whois.nic.barclays",
        "bargains" => "whois.donuts.co",
        "bauhaus" => "whois.nic.bauhaus",
        "bayern" => "whois-dub.mm-registry.com",
        "bbc" => "whois.nic.bbc",
        "bbva" => "whois.nic.bbva",
        "beer" => "whois-dub.mm-registry.com",
        "berlin" => "whois.nic.berlin",
        "best" => "whois.nic.best",
        "bibl.bi.bingo" => "whois.donuts.co",
        "bio" => "whois.ksregistry.net",
        "black" => "whois.afilias.net",
        "blackfriday" => "whois.uniregistry.net",
        "bloomber.blue" => "whois.afilias.net",
        "bmw" => "whois.ksregistry.net",
        "bnpparibas" => "whois.afilias-srs.net",
        "boats" => "whois.afilias-srs.net",
        "bond" => "whois.nic.bond",
        "boo" => "domain-registry-whois.l.google.com",
        "boutique" => "whois.donuts.co",
        "bridgestone" => "whois.nic.bridgestone",
        "broker" => "whois.nic.broker",
        "brother" => "whois.nic.brother",
        "brussels" => "whois.nic.brussels",
        "budapest" => "whois-dub.mm-registry.com",
        "build" => "whois.nic.build",
        "builders" => "whois.donuts.co",
        "business" => "whois.donuts.co",
        "buz.bzh" => "whois-bzh.nic.fr",
        "cab" => "whois.donuts.co",
        "cafe" => "whois.donuts.co",
        "cal" => "domain-registry-whois.l.google.com",
        "camera" => "whois.donuts.co",
        "camp" => "whois.donuts.co",
        "cancerresearch" => "whois.nic.cancerresearch",
        "canon" => "whois.nic.canon",
        "capetown" => "capetown-whois.registry.net.za",
        "capital" => "whois.donuts.co",
        "carava.cards" => "whois.donuts.co",
        "care" => "whois.donuts.co",
        "career" => "whois.nic.career",
        "careers" => "whois.donuts.co",
        "cars" => "whois.uniregistry.net",
        "cartie.casa" => "whois-dub.mm-registry.com",
        "cash" => "whois.donuts.co",
        "casino" => "whois.donuts.co",
        "catering" => "whois.donuts.co",
        "cb.center" => "whois.donuts.co",
        "ceo" => "whois.nic.ceo",
        "cern" => "whois.afilias-srs.net",
        "cfa" => "whois.nic.cfa",
        "cfd" => "whois.nic.cfd",
        "channel" => "domain-registry-whois.l.google.com",
        "chat" => "whois.donuts.co",
        "cheap" => "whois.donuts.co",
        "chlo.christmas" => "whois.uniregistry.net",
        "chrome" => "domain-registry-whois.l.google.com",
        "church" => "whois.donuts.co",
        "cisc.citi.city" => "whois.donuts.co",
        "claims" => "whois.donuts.co",
        "cleaning" => "whois.donuts.co",
        "click" => "whois.uniregistry.net",
        "clinic" => "whois.donuts.co",
        "clothing" => "whois.donuts.co",
        "club" => "whois.nic.club",
        "coach" => "whois.donuts.co",
        "codes" => "whois.donuts.co",
        "coffee" => "whois.donuts.co",
        "college" => "whois.nic.college",
        "cologne" => "whois-fe1.pdt.cologne.tango.knipp.de",
        "community" => "whois.donuts.co",
        "company" => "whois.donuts.co",
        "computer" => "whois.donuts.co",
        "condos" => "whois.donuts.co",
        "construction" => "whois.donuts.co",
        "consulting" => "whois.unitedtld.com",
        "contractors" => "whois.donuts.co",
        "cooking" => "whois-dub.mm-registry.com",
        "cool" => "whois.donuts.co",
        "corsica" => "whois-corsica.nic.fr",
        "country" => "whois-dub.mm-registry.com",
        "coupons" => "whois.donuts.co",
        "courses" => "whois.aridnrs.net.au",
        "credit" => "whois.donuts.co",
        "creditcard" => "whois.donuts.co",
        "cricket" => "whois.nic.cricket",
        "cr.cruises" => "whois.donuts.co",
        "cuisinella" => "whois.nic.cuisinella",
        "cymru" => "whois.nic.cymru",
        "cyou" => "whois.afilias-srs.net",
        "dabur" => "whois.afilias-srs.net",
        "dad" => "domain-registry-whois.l.google.com",
        "dance" => "whois.unitedtld.com",
        "dat.dating" => "whois.donuts.co",
        "datsun" => "whois.nic.gmo",
        "day" => "domain-registry-whois.l.google.com",
        "dclk" => "domain-registry-whois.l.google.com",
        "deals" => "whois.donuts.co",
        "degree" => "whois.rightside.co",
        "delivery" => "whois.donuts.co",
        "democrat" => "whois.unitedtld.com",
        "dental" => "whois.donuts.co",
        "dentist" => "whois.rightside.co",
        "desi" => "whois.ksregistry.net",
        "design" => "whois.nic.design",
        "dev" => "domain-registry-whois.l.google.com",
        "diamonds" => "whois.donuts.co",
        "diet" => "whois.uniregistry.net",
        "digital" => "whois.donuts.co",
        "direct" => "whois.donuts.co",
        "directory" => "whois.donuts.co",
        "discount" => "whois.donuts.co",
        "dn.docs" => "domain-registry-whois.l.google.com",
        "dog" => "whois.donuts.co",
        "doha" => "whois.nic.doha",
        "domains" => "whois.donuts.co",
        "doosan" => "whois.nic.doosan",
        "downloa.durban" => "durban-whois.registry.net.za",
        "dvag" => "whois.ksregistry.net",
        "eart.eat" => "domain-registry-whois.l.google.com",
        "education" => "whois.donuts.co",
        "email" => "whois.donuts.co",
        "emerck" => "whois.afilias-srs.net",
        "energy" => "whois.donuts.co",
        "engineer" => "whois.rightside.co",
        "engineering" => "whois.donuts.co",
        "enterprises" => "whois.donuts.co",
        "epson" => "whois.aridnrs.net.au",
        "equipment" => "whois.donuts.co",
        "erni" => "whois.nic.erni",
        "esq" => "domain-registry-whois.l.google.com",
        "estate" => "whois.donuts.co",
        "eurovision" => "whois.nic.eurovision",
        "eus" => "whois.eus.coreregistry.net",
        "events" => "whois.donuts.co",
        "everban.exchange" => "whois.donuts.co",
        "expert" => "whois.donuts.co",
        "exposed" => "whois.donuts.co",
        "express" => "whois.donuts.co",
        "fail" => "whois.donuts.co",
        "fait.fan" => "whois.centralnic.com",
        "fans" => "whois.nic.fans",
        "farm" => "whois.donuts.co",
        "fashion" => "whois-dub.mm-registry.com",
        "feedback" => "whois.nic.feedback",
        "film" => "whois.nic.film",
        "finance" => "whois.donuts.co",
        "financial" => "whois.donuts.co",
        "firmdale" => "whois.nic.firmdale",
        "fish" => "whois.donuts.co",
        "fishing" => "whois-dub.mm-registry.com",
        "fit" => "whois-dub.mm-registry.com",
        "fitness" => "whois.donuts.co",
        "flights" => "whois.donuts.co",
        "florist" => "whois.donuts.co",
        "flowers" => "whois.uniregistry.net",
        "flsmidth" => "whois.ksregistry.net",
        "fly" => "domain-registry-whois.l.google.com",
        "foo" => "domain-registry-whois.l.google.com",
        "football" => "whois.donuts.co",
        "forex" => "whois.nic.forex",
        "forsale" => "whois.unitedtld.com",
        "foundation" => "whois.donuts.co",
        "frl" => "whois.nic.frl",
        "frogans" => "whois-frogans.nic.fr",
        "fund" => "whois.donuts.co",
        "furniture" => "whois.donuts.co",
        "futbol" => "whois.unitedtld.com",
        "fyi" => "whois.donuts.co",
        "gal" => "whois.gal.coreregistry.net",
        "gallery" => "whois.donuts.co",
        "garden" => "whois-dub.mm-registry.com",
        "gbiz" => "domain-registry-whois.l.google.com",
        "gdn" => "whois.gdnregistry.com",
        "gent" => "whois.nic.gent",
        "ggee" => "whois.nic.ggee",
        "gift" => "whois.uniregistry.net",
        "gifts" => "whois.donuts.co",
        "gives" => "whois.rightside.co",
        "glass" => "whois.donuts.co",
        "gle" => "domain-registry-whois.l.google.com",
        "global" => "whois.nic.global",
        "globo" => "whois.gtlds.nic.br",
        "gmail" => "domain-registry-whois.l.google.com",
        "gm.gmx" => "whois-fe1.gmx.tango.knipp.de",
        "gold" => "whois.donuts.co",
        "goldpoint" => "whois.nic.goldpoint",
        "golf" => "whois.donuts.co",
        "goo" => "whois.nic.gmo",
        "goog" => "domain-registry-whois.l.google.com",
        "google" => "domain-registry-whois.l.google.com",
        "gop" => "whois-cl01.mm-registry.com",
        "graphics" => "whois.donuts.co",
        "gratis" => "whois.donuts.co",
        "green" => "whois.afilias.net",
        "gripe" => "whois.donuts.co",
        "guge" => "domain-registry-whois.l.google.com",
        "guide" => "whois.donuts.co",
        "guitars" => "whois.uniregistry.net",
        "guru" => "whois.donuts.co",
        "hamburg" => "whois.nic.hamburg",
        "hangout" => "domain-registry-whois.l.google.com",
        "haus" => "whois.unitedtld.com",
        "healthcare" => "whois.donuts.co",
        "help" => "whois.uniregistry.net",
        "here" => "domain-registry-whois.l.google.com",
        "hermes" => "whois.afilias-srs.net",
        "hiphop" => "whois.uniregistry.net",
        "hitachi" => "whois.nic.gmo",
        "hiv" => "whois.afilias-srs.net",
        "hockey" => "whois.donuts.co",
        "holdings" => "whois.donuts.co",
        "holiday" => "whois.donuts.co",
        "homedepot" => "whois.afilias-srs.net",
        "homes" => "whois.afilias-srs.net",
        "honda" => "whois.nic.honda",
        "horse" => "whois-dub.mm-registry.com",
        "host" => "whois.nic.host",
        "hosting" => "whois.uniregistry.net",
        "how" => "domain-registry-whois.l.google.com",
        "ibm" => "whois.nic.ibm",
        "icbc" => "whois.afilias-srs.net",
        "icu" => "whois.nic.icu",
        "ifm" => "whois.nic.ifm",
        "immo" => "whois.donuts.co",
        "immobilien" => "whois.unitedtld.com",
        "industries" => "whois.donuts.co",
        "infiniti" => "whois.nic.gmo",
        "ing" => "domain-registry-whois.l.google.com",
        "ink" => "whois.centralnic.com",
        "institute" => "whois.donuts.co",
        "insure" => "whois.donuts.co",
        "international" => "whois.donuts.co",
        "investments" => "whois.donuts.co",
        "irish" => "whois.afilias-srs.net",
        "iw.java" => "whois.nic.java",
        "jcb" => "whois.nic.gmo",
        "jetz.jewelry" => "whois.donuts.co",
        "jll" => "whois.afilias-srs.net",
        "joburg" => "joburg-whois.registry.net.za",
        "juegos" => "whois.uniregistry.net",
        "kaufen" => "whois.unitedtld.com",
        "kddi" => "whois.nic.kddi",
        "kim" => "whois.afilias.net",
        "kitchen" => "whois.donuts.co",
        "kiwi" => "whois.nic.kiwi",
        "koeln" => "whois-fe1.pdt.koeln.tango.knipp.de",
        "komatsu" => "whois.nic.komatsu",
        "krd" => "whois.aridnrs.net.au",
        "kre.kyoto" => "whois.nic.kyoto",
        "lacaixa" => "whois.nic.lacaixa",
        "land" => "whois.donuts.co",
        "lat" => "whois.nic.lat",
        "latrobe" => "whois.nic.latrobe",
        "lawyer" => "whois.rightside.co",
        "lds" => "whois.afilias-srs.net",
        "lease" => "whois.donuts.co",
        "leclerc" => "whois-leclerc.nic.fr",
        "legal" => "whois.donuts.co",
        "lgbt" => "whois.afilias.net",
        "liaison" => "whois.nic.liaison",
        "lidl" => "whois.nic.lidl",
        "life" => "whois.donuts.co",
        "lighting" => "whois.donuts.co",
        "limited" => "whois.donuts.co",
        "limo" => "whois.donuts.co",
        "lin.loa.loans" => "whois.donuts.co",
        "lol" => "whois.uniregistry.net",
        "london" => "whois-lon.mm-registry.com",
        "lotte" => "whois.nic.lotte",
        "lotto" => "whois.afilias.net",
        "love" => "whois.centralnic.com",
        "ltda" => "whois.afilias-srs.net",
        "lupi.luxe" => "whois-dub.mm-registry.com",
        "luxury" => "whois.nic.luxury",
        "madrid" => "whois.madrid.rs.corenic.net",
        "mai.maison" => "whois.donuts.co",
        "management" => "whois.donuts.co",
        "mango" => "whois.mango.coreregistry.net",
        "market" => "whois.rightside.co",
        "marketing" => "whois.donuts.co",
        "markets" => "whois.nic.markets",
        "marriott" => "whois.afilias-srs.net",
        "mba" => "whois.donuts.co",
        "media" => "whois.donuts.co",
        "meet" => "whois.afilias.net",
        "melbourne" => "whois.aridnrs.net.au",
        "meme" => "domain-registry-whois.l.google.com",
        "memorial" => "whois.donuts.co",
        "men" => "whois.nic.men",
        "menu" => "whois.nic.menu",
        "miami" => "whois-dub.mm-registry.com",
        "mini" => "whois.ksregistry.net",
        "mma" => "whois-mma.nic.fr",
        "moda" => "whois.unitedtld.com",
        "moe" => "whois.nic.moe",
        "monash" => "whois.nic.monash",
        "money" => "whois.donuts.co",
        "mormon" => "whois.afilias-srs.net",
        "mortgage" => "whois.rightside.co",
        "moscow" => "whois.nic.moscow",
        "motorcycles" => "whois.afilias-srs.net",
        "mov" => "domain-registry-whois.l.google.com",
        "movie" => "whois.donuts.co",
        "mtn" => "whois.nic.mtn",
        "mtpc" => "whois.nic.gmo",
        "nadex" => "whois.nic.nadex",
        "nagoy.navy" => "whois.rightside.co",
        "nec" => "whois.nic.nec",
        "network" => "whois.donuts.co",
        "neusta.new" => "domain-registry-whois.l.google.com",
        "news" => "whois.rightside.co",
        "nexus" => "domain-registry-whois.l.google.com",
        "ngo" => "whois.publicinterestregistry.net",
        "nh.nico" => "whois.nic.nico",
        "ninja" => "whois.unitedtld.com",
        "nissan" => "whois.nic.gmo",
        "nra" => "whois.afilias-srs.net",
        "nrw" => "whois.nic.nrw",
        "nt.ny.okinaw.one" => "whois.nic.one",
        "ong" => "whois.publicinterestregistry.net",
        "onl" => "whois.afilias-srs.net",
        "online" => "whois.centralnic.com",
        "ooo" => "whois.nic.ooo",
        "oracle" => "whois.nic.oracle",
        "organic" => "whois.afilias.net",
        "osaka" => "whois.nic.osaka",
        "otsuk.ovh" => "whois-ovh.nic.fr",
        "page" => "domain-registry-whois.l.google.com",
        "panera.paris" => "whois-paris.nic.fr",
        "partners" => "whois.donuts.co",
        "parts" => "whois.donuts.co",
        "part.pharmac.philips" => "whois.nic.philips",
        "photo" => "whois.uniregistry.net",
        "photography" => "whois.donuts.co",
        "photos" => "whois.donuts.co",
        "physio" => "whois.nic.physio",
        "piage.pics" => "whois.uniregistry.net",
        "picte.pictures" => "whois.donuts.co",
        "pink" => "whois.afilias.net",
        "pizza" => "whois.donuts.co",
        "place" => "whois.donuts.co",
        "plumbing" => "whois.donuts.co",
        "plus" => "whois.donuts.co",
        "pohl" => "whois.ksregistry.net",
        "poker" => "whois.afilias.net",
        "porn" => "whois.afilias-srs.net",
        "pos.prax.press" => "whois.nic.press",
        "prod" => "domain-registry-whois.l.google.com",
        "productions" => "whois.donuts.co",
        "prof" => "domain-registry-whois.l.google.com",
        "properties" => "whois.donuts.co",
        "property" => "whois.uniregistry.net",
        "pub" => "whois.unitedtld.com",
        "qpo.quebec" => "whois.nic.quebec",
        "racin.realto.recipes" => "whois.donuts.co",
        "red" => "whois.afilias.net",
        "redstone" => "whois.afilias-srs.net",
        "rehab" => "whois.rightside.co",
        "reise" => "whois.nic.reise",
        "reisen" => "whois.donuts.co",
        "reit" => "whois.nic.reit",
        "re.rent" => "whois.centralnic.com",
        "rentals" => "whois.donuts.co",
        "repair" => "whois.donuts.co",
        "repor.republican" => "whois.rightside.co",
        "rest" => "whois.centralnic.com",
        "restaurant" => "whois.donuts.co",
        "revie.reviews" => "whois.unitedtld.com",
        "rich" => "whois.afilias-srs.net",
        "rio" => "whois.gtlds.nic.br",
        "rip" => "whois.rightside.co",
        "rocks" => "whois.unitedtld.com",
        "rodeo" => "whois-dub.mm-registry.com",
        "rsvp" => "domain-registry-whois.l.google.com",
        "ruhr" => "whois.nic.ruhr",
        "run" => "whois.donuts.co",
        "ryuky.saarland" => "whois.ksregistry.net",
        "sale" => "whois.rightside.co",
        "samsung" => "whois.nic.samsung",
        "sandvik" => "whois.nic.sandvik",
        "sandvikcoromant" => "whois.nic.sandvikcoromant",
        "sap" => "whois.nic.sap",
        "sarl" => "whois.donuts.co",
        "saxo" => "whois.aridnrs.net.au",
        "sca" => "whois.nic.sca",
        "scb" => "whois.nic.scb",
        "schmidt" => "whois.nic.schmidt",
        "scholarships" => "whois.afilias-srs.net",
        "school" => "whois.donuts.co",
        "schule" => "whois.donuts.co",
        "schwarz" => "whois.nic.schwarz",
        "scienc.scot" => "whois.scot.coreregistry.net",
        "seat" => "whois.nic.seat",
        "sene.services" => "whois.donuts.co",
        "sew" => "whois.afilias-srs.net",
        "sex" => "whois.afilias-srs.net",
        "sexy" => "whois.uniregistry.net",
        "shiksha" => "whois.afilias.net",
        "shoes" => "whois.donuts.co",
        "show" => "whois.donuts.co",
        "shriram" => "whois.afilias-srs.net",
        "singles" => "whois.donuts.co",
        "site" => "whois.centralnic.com",
        "ski" => "whois.ksregistry.net",
        "sky" => "whois.nic.sky",
        "sncf" => "whois-sncf.nic.fr",
        "soccer" => "whois.donuts.co",
        "social" => "whois.unitedtld.com",
        "software" => "whois.rightside.co",
        "soh.solar" => "whois.donuts.co",
        "solutions" => "whois.donuts.co",
        "sony" => "whois.nic.sony",
        "soy" => "domain-registry-whois.l.google.com",
        "space" => "whois.nic.space",
        "spiegel" => "whois.ksregistry.net",
        "spreadbetting" => "whois.nic.spreadbetting",
        "study" => "whois.nic.study",
        "style" => "whois.donuts.co",
        "sucks" => "whois.nic.sucks",
        "supplies" => "whois.donuts.co",
        "supply" => "whois.donuts.co",
        "support" => "whois.donuts.co",
        "surf" => "whois-dub.mm-registry.com",
        "surgery" => "whois.donuts.co",
        "suzuk.swiss" => "whois.nic.swiss",
        "sydney" => "whois.nic.sydney",
        "systems" => "whois.donuts.co",
        "taipei" => "whois.nic.taipei",
        "tatar" => "whois.nic.tatar",
        "tattoo" => "whois.uniregistry.net",
        "tax" => "whois.donuts.co",
        "taxi" => "whois.donuts.co",
        "team" => "whois.donuts.co",
        "tech" => "whois.nic.tech",
        "technology" => "whois.donuts.co",
        "tel" => "whois.nic.tel",
        "temasek" => "whois.afilias-srs.net",
        "tennis" => "whois.donuts.co",
        "thd" => "whois.afilias-srs.net",
        "theater" => "whois.donuts.co",
        "tickets" => "whois.centralnic.com",
        "tienda" => "whois.donuts.co",
        "tips" => "whois.donuts.co",
        "tires" => "whois.donuts.co",
        "tirol" => "whois.nic.tirol",
        "today" => "whois.donuts.co",
        "toky.top" => "whois.nic.top",
        "toray" => "whois.nic.toray",
        "toshiba" => "whois.nic.toshiba",
        "tours" => "whois.donuts.co",
        "town" => "whois.donuts.co",
        "toys" => "whois.donuts.co",
        "trad.trading" => "whois.nic.trading",
        "training" => "whois.donuts.co",
        "trust" => "whois.nic.trust",
        "tui" => "whois.ksregistry.net",
        "university" => "whois.donuts.co",
        "un.uol" => "whois.gtlds.nic.br",
        "vacations" => "whois.donuts.co",
        "vegas" => "whois.afilias-srs.net",
        "ventures" => "whois.donuts.co",
        "versicherung" => "whois.nic.versicherung",
        "vet" => "whois.rightside.co",
        "viajes" => "whois.donuts.co",
        "video" => "whois.rightside.co",
        "villas" => "whois.donuts.co",
        "vision" => "whois.donuts.co",
        "vlaanderen" => "whois.nic.vlaanderen",
        "vodka" => "whois-dub.mm-registry.com",
        "vote" => "whois.afilias.net",
        "voting" => "whois.voting.tld-box.at",
        "voto" => "whois.afilias.net",
        "voyage" => "whois.donuts.co",
        "wales" => "whois.nic.wales",
        "walter" => "whois.nic.walter",
        "wang" => "whois.gtld.knet.cn",
        "watch" => "whois.donuts.co",
        "webca.website" => "whois.nic.website",
        "wed" => "whois.nic.wed",
        "wedding" => "whois-dub.mm-registry.com",
        "wei.whoswho" => "whois.nic.whoswho",
        "wien" => "whois.nic.wien",
        "wiki" => "whois.nic.wiki",
        "williamhil.wi.wme" => "whois.nic.wme",
        "work" => "whois-dub.mm-registry.com",
        "works" => "whois.donuts.co",
        "wtc" => "whois.nic.wtc",
        "wtf" => "whois.donuts.co",
        "xbo.xerox" => "whois.nic.xerox",
        "xin" => "whois.afilias-srs.net",
        "xxx" => "whois.nic.xxx",
        "xyz" => "whois.nic.xyz",
        "yachts" => "whois.afilias-srs.net",
        "yande.yodobashi" => "whois.nic.gmo",
        "yoga" => "whois-dub.mm-registry.com",
        "yokoham.youtube" => "domain-registry-whois.l.google.com",
        "zip" => "domain-registry-whois.l.google.com",
        "zone" => "whois.donuts.co",
        "zuerich" => "whois.ksregistry.net",
        "edu" => "whois.educause.net",
        "gov" => "whois.nic.gov",
        "mil" => "whois.nic.mil"
    );

    if($domainname){
        $domain_parts = explode(".", $domainname);
        $tld = strtolower(array_pop($domain_parts));
        $whoisserver = $whoisservers[$tld];

        if(($whoisinfo = fsockopen($whoisserver,$port)) == true){
            $output = "";
            fputs($whoisinfo,"$domainname\r\n");
            while(!feof($whoisinfo)) 
                $output .= fgets($whoisinfo,128); 
            fclose($whoisinfo);
        }
        echo "<pre class='result-card'>" . $output . "</pre>";
    }
?>